### ISSUE TITLE
Location Dropdown Menu for Iphone 8 SE blocked

### ISSUE THREAD

**Issue by DartyDart** [VeriFi-World/VeriFi#46]
1. The Add Network Interface, specifically the Location Drop down option is covered by the keyboard

2. This hinders the user able to confirm the location that the network is at and will stop them from contributing any Wi-Fis

3. Iphone 10 seems to be fine, however Iphone 8 is not compatible with adding networks for the app

4. Link below for a picture depicting this problem: 

https://discord.com/channels/1025506758527041649/1142242427533541377/1142917455182831726

**Comment by dale-lakes** [comment]
@DartyDart fixed
